### ISSUE TITLE
Some websites can still get the original IP

### ISSUE THREAD

**Issue by ajeecai** [Edu4rdSHL/tor-router#11]
Hi 

Thanks for this project, it works nicely. But when trying to check the IP in whatsmyip.com, the original public IP is still shown up. That is weird, because in most of the other checking IP website it works anonymously. Do you know why?

Thanks

**Comment by Edu4rdSHL** [comment]
Hello, can you try disabling JavaScript on your browser and visiting the site again? It may be some JavaScript thing leaking the data...

**Comment by ajeecai** [comment]
Not looking into the detailed, how is this tor-router working, is it routing all TCP traffic to tor? The traffic generated by JavaScript is also TCP so how can it be bypassed... Just curious.

**Comment by Edu4rdSHL** [comment]
I'm investigating, I tested locally, and the website is indeed getting the real IP address. And yes, the script routes **ALL** TCP traffic over Tor, but also DNS requests... not sure how's it getting leaked.

**Comment by Edu4rdSHL** [comment]
Please let me know if it's fixed for you.
