### ISSUE TITLE
impossible to download

### ISSUE THREAD

**Issue by xzj8b3** [Edu4rdSHL/tor-router#2]
git clone https://gitub.com/edu4rdshl/tor-router.git && cd ./tor-router && sudo bash install.sh
Clone in 'tor-router' in corso...
fatal: impossibile aggiornare l'URL di base dalla redirezione:
  richiesta: https://gitub.com/edu4rdshl/tor-router.git/info/refs?service=git-upload-pack
   redirect: http://www6.gitub.com/?s_token=1569786587.0018167796&kw=git&term=Code%20Repository&term=Secure%20Code%20Review&term=Programming%20Courses&backfill=0&tdfs=1

**Comment by Edu4rdSHL** [comment]
Hi, sorry for the typo in the documentation. It's github.com and no gitub.com.

**Comment by xzj8b3** [comment]
> Ciao, scusa per il refuso nella documentazione. È github.com e non gitub.com.

Okay... I didn't even notice
