### ISSUE TITLE
But to install it??

### ISSUE THREAD

**Issue by xzj8b3** [Edu4rdSHL/tor-router#3]
But to install it??  Does it work on Fedora?

**Comment by Edu4rdSHL** [comment]
Hello, follow the documentation.

**Comment by xzj8b3** [comment]
> Ciao, segui la documentazione.

is well what I have done and returns me command not found

**Comment by Edu4rdSHL** [comment]
Are you using Bash? What happens when you run `git clone https://github.com/edu4rdshl/tor-router.git && cd ./tor-router && sudo bash install.sh` ?

**Comment by xzj8b3** [comment]
> Stai usando Bash? Cosa succede quando corri `git clone https://github.com/edu4rdshl/tor-router.git && cd ./tor-router && sudo bash install.sh`?
> 
> mid dadi è una directory con la quale comando 

sudo./tor-route

**Comment by Edu4rdSHL** [comment]
I don'0t understand what are you saying, please write in English.

**Comment by xzj8b3** [comment]
> Non capisco cosa stai dicendo, per favore scrivi in ​​inglese.

doesn't work that script doesn't start service and using boot command you wrote you give me back that it's a directory
