### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by FaultierSP** [Edu4rdSHL/tor-router#6]
https://github.com/Edu4rdSHL/tor-router/blob/0bfd341c658ffebc65b43fc0a430e76193b832d8/files/tor-router#L26

I think you have a typo here. Didn't work until I changed it to "elif".

**Comment by Edu4rdSHL** [comment]
Hello, thanks. Can you make a pull request? It's appreciated.

**Comment by FaultierSP** [comment]
Done. I hope, I did it right, I am quite new to github. :)

**Comment by Edu4rdSHL** [comment]
Thank you, this was fine!
