### ISSUE TITLE
Routing with Tor

### ISSUE THREAD

**Issue by DaniLuMa** [Edu4rdSHL/tor-router#8]
Hola Eduardo:

Mi nombre es Daniel y estoy intentando enrutar el trafico a través la de la red Tor. He probado con varios programas TorGhostNG y alguno más, incluso con tor + iptables directamente y ahora con Tor-router. Todo funciona ok pero no hace lo que quiero. Lo que yo quiero es que no solo la máquina lleve todo el tráfico a la red tor sino que haga de router con dos interface y todo lo que le venta por cualquiera de ellas vaya a la red Tor y eso es lo que me falla. Me enruta a tor si salgo con el linux que tiene Tor o Tor-router pero tengo otra máquina conectada en otra red y sale a Internet pero normal, sin redirigir el tráfico a Tor. ¿Alguien tiene la misma necesidad que yo? ¿Pueden aydudarme?

Gracias de antemano
Saludos
Dani

Hi Eduardo:

My name is Daniel and I am trying to route traffic through the Tor network. I have tried with several TorGhostNG programs and some more, even with tor + iptables directly and now with Tor-router. Everything works ok but it doesn't do what I want. What I want is for the machine not only to carry all the traffic to the tor network but to act as a router with two interfaces and everything that is sold through any of them goes to the Tor network and that is what fails me. It routes me to tor if I go out with the linux that has Tor or Tor-router but I have another machine connected to another network and it goes to the Internet but normal, without redirecting the traffic to Tor. Does anyone have the same need as me? Can you help me?

Thanks in advance
Greetings
Dani

**Comment by DaniLuMa** [comment]
Hi people. I found this tutoria, it doesn't work but at the end, there is a comment fro Jef that fix the problem. If you follow it and change /etc/tor/torrc with the Jef lines It will be work fine. 

Regards
Dani

https://pimylifeup.com/raspberry-pi-tor-access-point/

Jef on January 22, 2021 at 9:13 am
FYI, the TransListenAddress and DNSListenAddress directives (deprecated in 0.2.9.2) no longer work and generate the following:

[warn] Skipping obsolete configuration option ‘TransListenAddress’
[warn] Skipping obsolete configuration option ‘DNSListenAddress’

This leaves the transparent proxies bound to 127.0.0.1, which doesn’t work. The address bindings are now made using x.x.x.x:xxxx format for the Port directives. The config should be:

Log notice file /var/log/tor/notices.log
VirtualAddrNetwork 10.192.0.0/10
AutomapHostsSuffixes .onion,.exit
AutomapHostsOnResolve 1
TransPort 192.168.220.1:9040
DNSPort 192.168.220.1:53

With that change, everything works great with current (2021-01-11) build of buster-lite.

Thanks for the tutorial.

**Comment by Edu4rdSHL** [comment]
@DaniLuMa that isn't the purpose of this script, it's just to redirect the local traffic.
